### ISSUE TITLE
Step fails with "Error: exists error"

### ISSUE THREAD

**Issue by unicornfingers** [marocchino/validate-dependabot#90]
I followed the instructions in the README to add this action to my repo, but when it runs, the `validate-dependabot` step fails with the message `Error: exists errors`. Because there is no further output, I'm not sure what's wrong or how to go about debugging it.

![Screen Shot 2021-05-28 at 12 43 22 AM](https://user-images.githubusercontent.com/70119906/119948535-c7c69780-bf4d-11eb-8ffd-09a6c7b122c5.png)

**Comment by marocchino** [comment]
You can print it in next step like:
```yaml
      - if: always()
        run: |
                  cat <<EOT 
                  ${{ steps.validate.outputs.markdown }}
                  EOT
```
 but you are right. Perhaps it would be appropriate to show more detailed error messages and what kind of error occurred in this step.

**Comment by marocchino** [comment]
a4d555f
